openapi: 3.0.0
info:
  title: Swagger
  description: Swagger
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:30202'
paths:
  '/dloan-interest/v1/accounts/{account_number}':
    get:
      tags:
        - disbursement
        - Inquiry
      summary: InquiryAccountInterestDetail
      description: Inquiry Account Interest Detail
      parameters:
        - name: x-request-id
          in: header
          schema:
            type: string
          required: false
          description: |-
            message id
            testst
            test
            test
          example: '{{message-id}}'
        - name: x-job-id
          in: header
          schema:
            type: string
          required: false
          description: job id
          example: '{{message-id}}'
        - name: x-real-ip
          in: header
          schema:
            type: number
          required: false
          description: real ip
          example: 127.0.0.1
        - name: x-caller-service
          in: header
          schema:
            type: string
          required: false
          description: coller service
          example: FrontEnd
        - name: x-caller-domain
          in: header
          schema:
            type: string
          required: false
          description: coller domain
          example: Front
        - name: datetime
          in: header
          schema:
            type: string
          required: false
          description: date time
          example: '{{datetime}}'
        - name: accept
          in: header
          schema:
            type: string
          required: false
          description: accept
          example: application/json
        - name: accept-language
          in: header
          schema:
            type: string
          required: false
          description: languate
        - name: accept-encoding
          in: header
          schema:
            type: string
          required: false
          description: encoding
        - name: Content-Type
          in: header
          schema:
            type: string
          required: false
          description: content type
          example: application/json
        - name: x-device
          in: header
          schema:
            type: string
          required: false
          description: device
        - name: x-application
          in: header
          schema:
            type: string
          required: false
          description: application
        - name: x-channel
          in: header
          schema:
            type: string
          required: false
          description: channel
        - name: user-agent
          in: header
          schema:
            type: string
          required: false
          description: agent
        - name: client_id
          in: header
          schema:
            type: string
          required: false
          description: client id
          example: '{{API_ClientId}}'
        - name: Access-Control-Allow-Origin
          in: header
          schema:
            type: string
          required: false
          description: access ctl origin
          example: '*'
        - name: Access-Control-Allow-Methods
          in: header
          schema:
            type: string
          required: false
          description: access ctl method
          example: 'GET, POST, DELETE, PUT, PATCH, OPTIONS'
        - name: Access-Control-Allow-Headers
          in: header
          schema:
            type: string
          required: false
          description: access ctl header
          example: 'Content-Type, api_key, Authorization'
        - name: account_number
          in: path
          schema:
            type: string
          required: true
          description: Number of account
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  rs_body:
                    properties:
                      account_number:
                        type: number
                        description: |-
                          Number of account
                          666
                      interest_index:
                        type: string
                      interest_index_rate:
                        type: number
                      interest_spread:
                        type: number
                      interest_rate:
                        type: number
                      interest_max_index:
                        type: string
                      interest_max_rate:
                        type: number
                      penalty_index:
                        type: string
                      penalty_rate:
                        type: number
                      grace_day:
                        type: number
                      catch_up_method:
                        type: number
                      oldest_stmt_due_date:
                        type: string
                      grace_end_date:
                        type: string
                      is_start_penalty:
                        type: boolean
                      unpaid_accrued_interest_amount:
                        type: number
                      unpaid_accrued_penalty_amount:
                        type: number
                      penalty_cal_method:
                        type: string
                      penalty_spread:
                        type: number
                      penalty_cal_rate:
                        type: number
                    title: rs_body
                    type: object
                    required:
                      - account_number
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    properties:
                      '0':
                        properties:
                          error_code:
                            type: string
                          error_type:
                            type: string
                          error_desc:
                            type: string
                          error_detail:
                            type: string
                        title: '0'
                        type: object
                    title: errors
                    type: object
