openapi: 3.0.0
info:
  title: Swagger
  description: Swagger
  version: 1.0.0
servers:
  - url: 'http://469edc11-fdb9-427e-96fb-c05191a29499.mock.pstmn.io'
paths:
  /test:
    post:
      tags:
        - interest
        - interest_index
      summary: >-
        [CalAccrual][DLoan][Set-1]_Open_Account_TC_Interest_calAccrual_ManualRepay_01
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                rq_header:
                  properties:
                    message-id:
                      type: string
                    x-job-id:
                      type: string
                    x-real-ip:
                      type: string
                    x-caller-service:
                      type: string
                    x-caller-domain:
                      type: string
                    datetime:
                      type: string
                    requested-service:
                      type: string
                    requested-service-version:
                      type: string
                    accept:
                      type: string
                    accept-language:
                      type: string
                    accept-encoding:
                      type: string
                    Content-Type:
                      type: string
                    x-device:
                      type: string
                    user-agent:
                      type: string
                    client_id:
                      type: string
                    secret:
                      type: string
                    x-application:
                      type: string
                    x-channel:
                      type: string
                    Fnx-Header:
                      type: string
                  title: '''rq_header'''
                  type: object
                  description: rq_header
                rq_body:
                  properties:
                    customer_number:
                      type: string
                    customer_type:
                      type: string
                    account_number:
                      type: string
                    account_name:
                      type: string
                    account_name_2:
                      type: string
                    credit_limit:
                      type: number
                    credit_term_number:
                      type: number
                    credit_term_unit:
                      type: string
                    product_name:
                      type: string
                    disbursement_account:
                      type: string
                    deduction_account:
                      type: string
                    account_branch:
                      type: number
                    application_id:
                      type: string
                    open_date:
                      type: string
                    maturity_date:
                      type: string
                    special_project_code:
                      type: string
                    finality_code:
                      type: string
                    external_product_code:
                      type: string
                    payment:
                      properties:
                        payment_frequency:
                          type: number
                        payment_unit:
                          type: string
                        payment_date:
                          type: number
                        billing_offset_day:
                          type: number
                      title: '''payment'''
                      type: object
                    interest:
                      properties:
                        interest_index:
                          type: string
                          description: interest_index
                          required:
                            - interest_index
                        interest_spread:
                          type: number
                      title: '''interest'''
                      type: object
                    plan:
                      properties:
                        interest_plan_name:
                          type: string
                        penalty_plan_name:
                          type: string
                        transaction_plan_name:
                          type: string
                        payment_plan_name:
                          type: string
                        grace_plan_name:
                          type: string
                      title: '''plan'''
                      type: object
                  title: '''rq_body'''
                  type: object
      parameters:
        - name: x-request-id
          in: header
          schema:
            type: string
          description: x-request-id
        - name: x-job-id
          in: header
          schema:
            type: string
        - name: x-real-ip
          in: header
          schema:
            type: number
        - name: x-caller-service
          in: header
          schema:
            type: string
        - name: x-caller-domain
          in: header
          schema:
            type: string
        - name: datetime
          in: header
          schema:
            type: string
        - name: accept
          in: header
          schema:
            type: string
        - name: accept-language
          in: header
          schema:
            type: string
        - name: accept-encoding
          in: header
          schema:
            type: string
        - name: Content-Type
          in: header
          schema:
            type: string
        - name: x-device
          in: header
          schema:
            type: string
        - name: user-agent
          in: header
          schema:
            type: string
        - name: client_id
          in: header
          schema:
            type: string
        - name: secret
          in: header
          schema:
            type: string
        - name: x-application
          in: header
          schema:
            type: string
        - name: x-channel
          in: header
          schema:
            type: string
        - name: user-agent
          in: header
          schema:
            type: string
        - name: Fnx-Header
          in: header
          schema:
            type: string
      responses:
        '200':
          description: success status 200
          content:
            application/json:
              schema:
                type: object
                properties:
                  rs_body:
                    type: string
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  rs_body:
                    type: string
