openapi: 3.0.0
info:
  title: OpenAccount
  version: 1.0.0
servers:
  - url: >-
      undefined://{{url-smith-dloan-account-management}}{{endpoint-dloan-open-account}}
paths:
  /:
    post:
      tags:
        - General
      summary: OpenAccount
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                rq_body:
                  customer_number: '111111111111'
                  customer_type: '0702'
                  account_name: นางสาวน้ำหนึ่ง ใจดี
                  account_name_en: Miss Namneung Jaidee
                  credit_limit: 350000
                  credit_term_number: 12
                  credit_term_unit: M
                  product_name: '7200120090005'
                  disbursement_account: '20000002020'
                  account_branch: 1
                  response_unit: 1
                  application_id: APP0001
                  payment:
                    payment_frequency: 1
                    payment_unit: M
                    payment_date: 31
                    payment_calculation_method: installment
                  interest:
                    interest_index: FIXED
                    interest_spread: 19
                  user_id: xxx1
                  service_branch: 1
              properties:
                rq_body:
                  properties:
                    customer_number:
                      type: string
                      description: description
                    customer_type:
                      type: string
                      description: description
                    account_name:
                      type: string
                      description: description
                    account_name_en:
                      type: string
                      description: description
                    credit_limit:
                      type: number
                      description: description
                    credit_term_number:
                      type: number
                      description: description
                    credit_term_unit:
                      type: string
                      description: description
                    product_name:
                      type: string
                      description: description
                    disbursement_account:
                      type: string
                      description: description
                    account_branch:
                      type: number
                      description: description
                    response_unit:
                      type: number
                      description: description
                    application_id:
                      type: string
                      description: description
                    payment:
                      properties:
                        payment_frequency:
                          type: number
                          description: description
                        payment_unit:
                          type: string
                          description: description
                        payment_date:
                          type: number
                          description: description
                        payment_calculation_method:
                          type: string
                          description: description
                      title: '''payment'''
                      type: object
                      example: &ref_0
                        payment_frequency: 1
                        payment_unit: M
                        payment_date: 31
                        payment_calculation_method: installment
                      description: description
                    interest:
                      properties:
                        interest_index:
                          type: string
                          description: description
                        interest_spread:
                          type: number
                          description: description
                      title: '''interest'''
                      type: object
                      example: &ref_1
                        interest_index: FIXED
                        interest_spread: 19
                      description: description
                    user_id:
                      type: string
                      description: description
                    service_branch:
                      type: number
                      description: description
                  title: '''rq_body'''
                  type: object
                  example:
                    customer_number: '111111111111'
                    customer_type: '0702'
                    account_name: นางสาวน้ำหนึ่ง ใจดี
                    account_name_en: Miss Namneung Jaidee
                    credit_limit: 350000
                    credit_term_number: 12
                    credit_term_unit: M
                    product_name: '7200120090005'
                    disbursement_account: '20000002020'
                    account_branch: 1
                    response_unit: 1
                    application_id: APP0001
                    payment: *ref_0
                    interest: *ref_1
                    user_id: xxx1
                    service_branch: 1
                  description: description
      parameters:
        - name: x-request-id
          in: header
          schema:
            type: string
          example: '{{message-id}}'
        - name: x-job-id
          in: header
          schema:
            type: string
          example: '{{message-id}}'
        - name: x-real-ip
          in: header
          schema:
            type: number
          example: 127.0.0.1
        - name: x-caller-service
          in: header
          schema:
            type: string
          example: FrontEnd
        - name: x-caller-domain
          in: header
          schema:
            type: string
          example: Front
        - name: datetime
          in: header
          schema:
            type: string
          example: '{{datetime}}'
        - name: accept
          in: header
          schema:
            type: string
          example: application/json
        - name: accept-language
          in: header
          schema:
            type: string
        - name: accept-encoding
          in: header
          schema:
            type: string
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: x-device
          in: header
          schema:
            type: string
        - name: user-agent
          in: header
          schema:
            type: string
        - name: client_id
          in: header
          schema:
            type: string
          example: '{{API_ClientId}}'
        - name: secret
          in: header
          schema:
            type: string
          example: '{{API_ClientSecret}}'
        - name: x-application
          in: header
          schema:
            type: string
        - name: x-channel
          in: header
          schema:
            type: string
        - name: user-agent
          in: header
          schema:
            type: string
        - name: Fnx-Header
          in: header
          schema:
            type: string
          example: '{"identity":{"userRoles":["developer"]}}'
        - name: customer_number
          in: query
          schema:
            type: string
          example: xxxx
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
